mysql> SELECT * FROM Enrolments RIGHT JOIN Students ON studentId=id;
+-----------+------------------+----------+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+---------+------------+
| StudentId | name             | enrolled | id | name                 | classroom | notes                                                                                                                                                                                                                                        | City | Country | PostalCode |
+-----------+------------------+----------+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+---------+------------+
|         1 | Hymie Parrington |        1 |  1 | Linnell McLanachan   | 1A        | Likes Data                                                                                                                                                                                                                                   | NULL | NULL    |       NULL |
|      NULL | NULL             |     NULL |  2 | Lorianna Henrion     | 1A        | Loves Data                                                                                                                                                                                                                                   | NULL | NULL    |       NULL |
|      NULL | NULL             |     NULL |  3 | Corena Edgeson       | 1A        | Cannot get enough of data                                                                                                                                                                                                                    | NULL | NULL    |       NULL |
|      NULL | NULL             |     NULL |  4 | Archaimbaud Lougheid | 2A        | Would rather do nothing other than sit down in front of a mountain of data and read through it like a book. SERIOUSLY needs to seek help about this because there is no way it is healthy for this person to like data any more than they do | NULL | NULL    |       NULL |
|      NULL | NULL             |     NULL |  5 | Dun Pettet           | 2A        | NULL                                                                                                                                                                                                                                         | NULL | NULL    |       NULL |
|      NULL | NULL             |     NULL |  6 | Hymie Parrington     | 2A        | Enjoys the Star Wars prequels                                                                                                                                                                                                                | NULL | NULL    |       NULL |
+-----------+------------------+----------+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+---------+------------+
6 rows in set (0.02 sec)
